@startuml IssueAggregate
class Issue {
  + issueId : UUID
  + title   : IssueTitle
  + status  : IssueStatus
}
note right of Issue
  担当者のみステータス変更可
end note

'── Issue集約専用のVO／Enum ───────────────────
class IssueTitle <<ValueObject>>
note right of IssueTitle
  1〜20文字以内
end note

enum IssueStatus <<Enum>> {
  Unstarted
  InReview
  Done
}

@enduml