@startuml DomainOverview

package "Team Aggregate"  <<Aggregate>> {
  !include team/aggregate.puml
}
package "User Aggregate"  <<Aggregate>> {
  !include user/aggregate.puml
}
package "Issue Aggregate" <<Aggregate>> {
  !include issue/aggregate.puml
}

Team "1" -- "3..*" User : "members" >
Pair "1" -- "2..3" User : "members" >
Team "1" -- "0..*" Pair : "" >
Issue "1" --> "1" User : "creator" >
Issue "1" --> "0..1" User : "assignee" >

@enduml
