name: build-uml
on:
  push:
    paths: ['docs/domain/**/*.puml']

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Java
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # PlantUML JAR
      - name: Download PlantUML
        run: curl -sL https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar -o plantuml.jar

      # Graphviz
      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      # Render (verbose + failfast2)
      - name: Generate SVG
        run: |
          cd docs/domain
          java -jar ../../plantuml.jar \
               -verbose -failfast2 -tsvg \
               -o . overview.puml \
               -filename overview

      # Check & commit
      - name: Commit SVG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ -f docs/domain/DomainOverview.svg ]]; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add docs/domain/DomainOverview.svg
            git commit -m "chore(svg): update overview diagram" || echo "no change"
            git push
          else
            echo "::error::DomainOverview.svg was not generated"
            exit 1
          fi
