name: build-uml
on:
  push:
    paths: [ 'docs/domain/**/*.puml' ]
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PlantUML + Graphviz
        run: sudo apt-get update && sudo apt-get install -y plantuml graphviz
      - name: Generate SVG
        run: |
          plantuml -tsvg docs/domain/overview.puml
      - name: Commit SVG
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/domain/overview.svg
          git commit -m "chore(svg): update overview diagram" || echo "no change"
          git push
